# Generated by Django 5.0.7 on 2024-09-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_profile_identity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['date']},
        ),
    ]
