# Generated by Django 5.0.7 on 2024-09-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_profile_gender_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, default='https://instagram.com/', null=True),
        ),
    ]
