# Generated by Django 5.0.7 on 2024-10-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallet',
        ),
    ]
