# Generated by Django 5.0.7 on 2024-09-23 16:54

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_facebook_hotel_instagram_hotel_linkedin_and_more'),
        # ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='hotel',
        #     name='tags',
        # ),
        # migrations.AddField(
        #     model_name='hotel',
        #     name='tags',
        #     field=taggit.managers.TaggableManager(
        #         blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        # ),
    ]
