# Generated by Django 5.0.7 on 2024-09-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_coupon_hotel_coupons_couponusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='hotel.coupon'),
        ),
    ]
