# Generated by Django 5.0.7 on 2024-09-26 04:43

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_booking_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='success_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', blank=True, length=10, max_length=20, null=True, prefix=''),
        ),
    ]
