# Generated by Django 5.0.7 on 2024-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_booking_success_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Canceled', 'Canceled'), ('Initiated', 'Initiated'), ('Refunding', 'Refunding'), ('Refunded', 'Refunded'), ('Unpaid', 'Unpaid'), ('Expired', 'Expired')], max_length=100),
        ),
    ]
