# Generated by Django 5.0.7 on 2024-10-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='couponusers',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='couponusers',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='hotelfaqs',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffonduty',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponUsers',
        ),
        migrations.DeleteModel(
            name='HotelFAQs',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='StaffOnDuty',
        ),
    ]
