# Generated by Django 5.0.7 on 2024-10-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_hotel_tags'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='hotel',
        #     name='tags',
        # ),
    ]
