# Generated by Django 5.0.7 on 2024-10-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_hotel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='views',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Under Maintanence', 'Under Maintenance'), ('Closed', 'Closed')], default='Live', max_length=20),
        ),
    ]
