# Generated by Django 5.0.7 on 2024-10-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_remove_hotel_views_alter_hotel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='featured',
        ),
    ]
