# Generated by Django 5.0.7 on 2024-10-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_remove_hotel_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='before_discount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='saved',
        ),
    ]
