"""
Django settings for Sleepify project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from environs import Env
env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-30sas@^u)c7orxng+=1bzf27x(0pwe_#p@80mj-0-sae(=75!e'

# SECURITY WARNING: don't run with debug turned on in production!
# The DEBUG setting is True by default for development purposes. Turn it off in production.
DEBUG = True

# ALLOWED_HOSTS is a list of strings representing the host/domain names that this Django site can serve.
# Add domain names here when deploying to production.
ALLOWED_HOSTS = []
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'


# Application definition
# These are the installed apps (Django apps and third-party apps) available in the project.
INSTALLED_APPS = [
    'jazzmin',

    # 'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom Apps
    'userauths',
    'user_dashboard',
    'hotel',
    'booking',

    # Third Party Apps
    'import_export',
    'crispy_forms',
    'mathfilters',
    'django_ckeditor_5',
    # 'ckeditor',
    'ckeditor_uploader',
    # 'taggit',
    # 'anymail',

]


# Middleware are classes that process requests and responses.
# They modify how the request passes through the Django app before reaching the view.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
]

# SESSION_ENGINE = 'django.contrib.sessions.backends.db'


# CORS_ALLOWED_ORIGINS = [
#     'http://your-frontend-domain.com',
#     'http://localhost:8000',
# ]

# The root URL configuration. Tells Django where to find the URL dispatcher.
ROOT_URLCONF = 'Sleepify.urls'

# Template settings, including the directories where Django will search for HTML template files.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sleepify.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Database Connection
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation settings for better security.
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization settings for language and time zone.
# https://docs.djangoproject.com/en/5.1/topics/i18n/
# For example, 'en-us' for US English and 'UTC' for Coordinated Universal Time.

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Media files (user-uploaded content) settings.
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
# Specifies the type of auto-incrementing field Django will use for primary keys.

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model setting
# Django allows the use of a custom user model. Instead of the default user model, we're using "userauths.User".
# AUTH_USER_MODEL = "userauths.User"
AUTH_USER_MODEL = "userauths.User"

# Stripe API keys for handling payment integration
# These are the secret and public keys used to interact with Stripe for payment processing.
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")
STRIPE_PUBLIC_KEY = env("STRIPE_PUBLIC_KEY")

# Website Address
# This is the base URL of the website. It is loaded from environment variables.
WEBSITE_ADDRESS = env("WEBSITE_ADDRESS")

# Email backend configuration
# Specifies the backend used for sending emails (e.g., SMTP, console, or other third-party services).
# Anymail
EMAIL_BACKEND = env("EMAIL_BACKEND")

# Default email address for the "from" field in emails
# When sending emails from the application, this email will be shown as the sender.
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")

# Anymail configuration for email service (Mailgun integration)
# Mailgun API keys and sender domain are set up for sending transactional emails through Mailgun.
ANYMAIL = {
    "MAILGUN_API_KEY": env("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": env("MAILGUN_SENDER_DOMAIN"),
    # "MAILERSEND_API_TOKEN": env("MAILERSEND_API_TOKEN"),
}

# URL for login redirection
# Users who are not logged in will be redirected to this URL when trying to access restricted views.
LOGIN_URL = "userauths:sign-in"

# URL for logout redirection
# After logging out, users will be redirected to this URL.
LOGOUT_REDIRECT_URL = "userauths:sign-in"

# Custom Admin Settings (Jazzmin)
# Jazzmin is a package used to customize Django's admin interface. This dictionary is for customizing the admin UI.
JAZZMIN_SETTINGS = {
    "site_title": "Sleepify",
    "site_header": "Sleepify",
    "site_brand": "Sleepify ",
    # "site_icon": "assets/logo/favicon.png",
    # "site_logo": "assets/logo/favicon.png",
    "welcome_sign": "Welcome to Sleepify! Login Now.",
    "copyright": "Sleepify",
    "user_avatar": "images/photos/logo.jpg",
    "topmenu_links": [
        {"name": "Home", "url": "admin:index",
            "permissions": ["auth.view_user"]},

        {"model": "AUTH_USER_MODEL.User"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,

    "order_with_respect_to": [
        "hotel",
        "hotel.Hotel",
        # "hotel.Hotel",
        "hotel.Room",
        "hotel.Booking",
        "hotel.BookingDetail",
        "hotel.Guest",
        "userauths",
    ],

    "icons": {
        "admin.LogEntry": "fas fa-file",

        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",

        "userauths.User": "fas fa-user",
        "userauths.Profile": "fas fa-address-card",

        "hotel.Hotel": "fas fa-home",
        "hotel.Booking": "fas fa-calendar-week",
        "hotel.BookingDetail": "fas fa-calendar-alt",
        "hotel.Guest": "fas fa-user",
        "hotel.Room": "fas fa-bed",
        "hotel.RoomType": "fas fa-bed",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    "related_modal_active": False,

    "custom_js": None,
    "show_ui_builder": True,

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

# UI tweaks for the Jazzmin admin interface
# These settings allow fine-tuning the appearance and layout of the admin interface.
# Jazzmin UI Tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-teal",
    "accent": "accent-success",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-light-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "lumen",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

# CKEditor 5 configuration settings
# CKEditor is a rich text editor. These settings can be customized based on specific needs (e.g., toolbar, styles).
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "imageUpload"
        ],
    },
    "comment": {
        "language": {"ui": "en", "content": "en"},
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
    },
    "extends": {
        "language": "en",
        "enterMode": 2,
        "shiftEnterMode": 1,
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
        ],
        "toolbar": [
            # "heading",
            # "|",

            # "|",
            "bold",
            "italic",
            # "link",
            "underline",
            "strikethrough",
            "code",
            # "subscript",
            # "superscript",
            "highlight",
            "|",
            "bulletedList",
            # "codeBlock",
            # "numberedList",
            # "todoList",
            # "|",
            "outdent",
            "indent",
            # "|",
            "blockQuote",
            "insertImage",
            # "|",
            "fontSize",
            # "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            # "mediaEmbed",
            "removeFormat",
            "insertTable",
            # "sourceEditing",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
                "toggleImageCaption",
                "|"
            ],
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
            "tableProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
            "tableCellProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph",
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1",
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2",
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3",
                },
            ]
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True,
            }
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True,
                    "classes": True, "styles": True}
            ]
        },
    },
}
